### ISSUE TITLE
Checklist for Day 2 Deliverables

### ISSUE THREAD

**Issue by Davidschlundtbodien** [sarahrudy/quiz-me#1]
### Due 10am Sep 10
- [ ] MVP summary with a description the problem you are solving and your audience (be specific and don’t be afraid to narrow your audience!)
- [ ] The API you will use
- [ ] DTR (be as actionable, detailed, and specific as you can)
- [ ] Wireframes of your application (using any electronic or hand-drawn tool you would like)
- [ ] Links to your design inspirations, with description of what you hope to replicate in your project
- [ ] Links to your repos
- [x] Project management tool (with some cards filled out and assigned to team members)
- [ ] A plan for how you will learn the stretch technology together as a group
